<a href="https://colab.research.google.com/github/Rutujkakde25/Pytorch-/blob/main/pytorch_collab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A tensor is a multidimensional array used to store and manipulate numerical data efficiently. In PyTorch, tensors support GPU acceleration and automatic differentiation, making them the fundamental data structure for deep learning.

In [ ]:
import torch

In [ ]:
x = torch.tensor(10)

print(x)

tensor(10)


In [ ]:
x=torch.tensor([1,2,3,4,5,25])
x

tensor([ 1,  2,  3,  4,  5, 25])

In [ ]:
x=torch.tensor([[1,2],
                [2,4]])
x

tensor([[1, 2],
        [2, 4]])

In [ ]:
x=torch.tensor([
    [1,3,4],
    [2,4,6],
    [3,6,9]
])
print(x.shape)

torch.Size([3, 3])


In [ ]:
x = torch.tensor([1,2,3])

print(x.dtype)

torch.int64


Check Device

print(x.device)

Output (if running on CPU)

>>cpu

If moved to GPU, it might show:

>>cuda:0

In [ ]:
# Number of Elements
x=torch.tensor([
    [1,3,4],
    [2,4,6],
    [3,6,9]
])

print(x.numel())

9


1. torch.zeros()

Creates a tensor filled with 0s.


In [ ]:

x = torch.zeros(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# for ones
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# for empty sapces/
x = torch.empty(2, 3)
print(x)

tensor([[2.2749e-36, 0.0000e+00, 2.3617e-33],
        [0.0000e+00, 0.0000e+00, 7.0065e-45]])


In [ ]:
# assigned random numbers BETWEEN 0 TO 1  (0-1) HERE USE "rand"
x = torch.rand(2, 3)
print(x)

tensor([[0.1635, 0.3860, 0.1012],
        [0.3564, 0.5409, 0.6296]])


In [ ]:
# 6. torch.arange()
# Works like Python's range().

x = torch.arange(0, 20, 2)
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


torch.eye()

Creates an identity matrix.


In [ ]:
x = torch.eye(4)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


Q: What is the difference between torch.rand() and torch.randn()?

Answer:

torch.rand() generates random numbers from a uniform distribution between 0 and 1.
torch.randn() generates random numbers from a normal (Gaussian) distribution with mean 0 and standard deviation 1.

This is a very common PyTorch interview question.

Q: What is the difference between torch.tensor() and torch.Tensor()?

Answer:

torch.tensor() is a function that creates a tensor from existing data and automatically infers its data type. torch.Tensor() is a class constructor that creates a float32 tensor by default and can also create an uninitialized tensor when given dimensions. In modern PyTorch code, torch.tensor() is the recommended way to create tensors.

In [ ]:
import torch

x = torch.tensor(3.0, requires_grad=True)

y = x ** 2

y.backward()

print("y =", y)
print("dy/dx =", x.grad)


y = tensor(9., grad_fn=<PowBackward0>)
dy/dx = tensor(6.)


In [ ]:
import torch

# ============================================
# STEP 1: Create Training Data
# ============================================

# Input (x)
x = torch.tensor([1.0, 2.0, 3.0, 4.0])

# Correct Output (y)
y_true = torch.tensor([2.0, 4.0, 6.0, 8.0])

# ============================================
# STEP 2: Initialize Weight
# ============================================

# Start with a random weight
w = torch.tensor(0.0, requires_grad=True)

# ============================================
# STEP 3: Hyperparameters
# ============================================

learning_rate = 0.01
epochs = 20

# ============================================
# STEP 4: Training Loop
# ============================================

for epoch in range(epochs):

    # -----------------------------
    # Forward Pass
    # -----------------------------
    y_pred = w * x

    # -----------------------------
    # Calculate Loss (Mean Squared Error)
    # -----------------------------
    loss = ((y_pred - y_true) ** 2).mean()

    # -----------------------------
    # Backward Pass
    # Compute Gradient
    # -----------------------------
    loss.backward()

    # -----------------------------
    # Update Weight
    # -----------------------------
    with torch.no_grad():
        w -= learning_rate * w.grad

    # -----------------------------
    # Print Progress
    # -----------------------------
    print(
        f"Epoch {epoch+1:2d} | "
        f"Weight = {w.item():.4f} | "
        f"Loss = {loss.item():.4f}"
    )

    # -----------------------------
    # Clear Gradient
    # -----------------------------
    w.grad.zero_()

# ============================================
# Final Weight
# ============================================

print("\nTraining Finished")
print("Final Weight =", w.item())

Epoch  1 | Weight = 0.3000 | Loss = 30.0000
Epoch  2 | Weight = 0.5550 | Loss = 21.6750
Epoch  3 | Weight = 0.7717 | Loss = 15.6602
Epoch  4 | Weight = 0.9560 | Loss = 11.3145
Epoch  5 | Weight = 1.1126 | Loss = 8.1747
Epoch  6 | Weight = 1.2457 | Loss = 5.9062
Epoch  7 | Weight = 1.3588 | Loss = 4.2673
Epoch  8 | Weight = 1.4550 | Loss = 3.0831
Epoch  9 | Weight = 1.5368 | Loss = 2.2275
Epoch 10 | Weight = 1.6063 | Loss = 1.6094
Epoch 11 | Weight = 1.6653 | Loss = 1.1628
Epoch 12 | Weight = 1.7155 | Loss = 0.8401
Epoch 13 | Weight = 1.7582 | Loss = 0.6070
Epoch 14 | Weight = 1.7945 | Loss = 0.4385
Epoch 15 | Weight = 1.8253 | Loss = 0.3168
Epoch 16 | Weight = 1.8515 | Loss = 0.2289
Epoch 17 | Weight = 1.8738 | Loss = 0.1654
Epoch 18 | Weight = 1.8927 | Loss = 0.1195
Epoch 19 | Weight = 1.9088 | Loss = 0.0863
Epoch 20 | Weight = 1.9225 | Loss = 0.0624

Training Finished
Final Weight = 1.9224810600280762


1. loss.backward()
Definition

loss.backward() starts the backward pass. It tells PyTorch's Autograd engine to compute the gradients (derivatives) of the loss with respect to all tensors that have requires_grad=True.

What happens internally?
PyTorch traverses the computation graph from the loss back to the parameters.
It applies the Chain Rule to compute derivatives.
The computed gradients are stored in the .grad attribute of each parameter.

Example:

loss.backward()

print(w.grad)

Output:

tensor(-16.)

Here, w.grad contains:

d(Loss) / d(Weight)
2. w.grad
Definition

w.grad stores the gradient (derivative) of the loss with respect to the weight.

Mathematically:

w.grad = d(Loss) / dw
Purpose

The gradient tells us:

How should the weight change to reduce the loss?

Remember:

w = Weight (parameter)
w.grad = Slope of the loss function

Example:

Weight = 3

Gradient = -16

The weight is still 3. The gradient only tells us how to update it.

3. Why is the Gradient Needed?

A neural network learns by changing its weights.

The gradient answers the question:

"If I change this weight slightly, how will the loss change?"

Positive gradient → Decrease the weight
Negative gradient → Increase the weight
Zero gradient → Already near the minimum loss

Without gradients, the model cannot learn.

4. Learning Rate
learning_rate = 0.1
Definition

The learning rate controls how big each update step should be.

Formula:

New Weight = Old Weight − Learning Rate × Gradient

Example:

Old Weight = 3

Gradient = -16

Learning Rate = 0.1

New Weight

= 3 − (0.1 × -16)

= 4.6
Small Learning Rate

Advantages:

Stable training
Accurate learning

Disadvantages:

Slow training
Large Learning Rate

Advantages:

Faster learning

Disadvantages:

Can overshoot the minimum
Training may become unstable
5. Weight Update
w -= learning_rate * w.grad

Equivalent to:

w = w - learning_rate * w.grad
Purpose

This updates the weight using the gradient computed by Autograd.

This process is called Gradient Descent.

Without updating the weights, the model will never improve.

6. torch.no_grad()
with torch.no_grad():
Definition

Temporarily disables gradient tracking.

Why is it needed?

During the forward pass, PyTorch records every operation to build the computation graph.

Example:

y = w * x

This operation is recorded because gradients will be needed later.

However, when updating the weight:

w -= learning_rate * w.grad

we are not performing part of the neural network computation.

We are simply changing the value of the parameter.

If PyTorch tracked this update, it would create unnecessary computation graphs, consume more memory, and could lead to incorrect behavior.

Therefore, we use:

with torch.no_grad():

which means:

"Do not track any operations inside this block."

Benefits
Saves memory
Faster execution
Prevents unnecessary computation graphs
7. w.grad.zero_()
w.grad.zero_()
Definition

Resets the gradient stored in w.grad to zero.

Why is it needed?

PyTorch accumulates gradients by default.

Example:

First backward pass:

Gradient = -16

Second backward pass:

Gradient = -32

Third backward pass:

Gradient = -48

because gradients are added together.

Before computing the next gradient, we must clear the previous one.

w.grad.zero_()

Now:

Gradient = 0

The next backward pass computes a fresh gradient.

8. Why Does PyTorch Accumulate Gradients?

Gradient accumulation is useful when training large models.

Example:

Instead of processing:

1024 images

at once, we process:

Batch 1
↓

Compute Gradient

↓

Batch 2

↓

Add Gradient

↓

Batch 3

↓

Add Gradient

↓

Update Weight Once

This technique is called Gradient Accumulation.

For normal training, however, we clear the gradients after every update.

9. Complete Training Flow
Initialize Weight
        │
        ▼
Forward Pass
        │
        ▼
Prediction
        │
        ▼
Calculate Loss
        │
        ▼
loss.backward()
        │
        ▼
Compute Gradient
        │
        ▼
Gradient Stored in w.grad
        │
        ▼
with torch.no_grad()
        │
        ▼
Update Weight
        │
        ▼
w.grad.zero_()
        │
        ▼
Next Epoch
10. Complete Code
# Forward Pass
y_pred = w * x

# Compute Loss
loss = ((y_pred - y_true) ** 2).mean()

# Backward Pass
loss.backward()

# Update Weight
with torch.no_grad():
    w -= learning_rate * w.grad

# Clear Gradient
w.grad.zero_()